### PR TITLE
Support JWK thumbprints as key ids

### PR DESCRIPTION
**Pull request by anakinj**
This addresses #474.

Allow the default and custom kid generation to be changed to a more "standard" way of generating JWK kids.

Also introduces a configuration concept via`::JWK.configuration` where the default values has been moved.

Would very much like to deprecate the current way of kid generation, but we would need to notify about the deprecation in some way before that.

### CODE REVIEW

**Review by excpt — CHANGES_REQUESTED** [review]
Please update the version.rb to 3.0.0.dev

It's an API breaking change. 

Great work! 👍

**Comment by anakinj** [comment]
The API should not have changed in this case, the intention was that at least. What API do you have on your mind?

**Comment by anakinj** [comment]
@excpt got very curious on what im missing:)

**Comment by excpt** [comment]
I see that I have chosen my word poorly. 😖 

Clarification:

You want to depricate the current used way of kid generation.

This will break existing implementations while continuing using the 2.x versions of this gem.

I recommend bumping the version to 3.0 in that case. So this is will be clear for all the direct and mostly indirect users of this gem.

This allows us to continue the development and it's still possible to continue supporting the 2.x versions.

**Comment by anakinj** [comment]
Thanks for the clarification 👍 . I will in my turn clarify my thoughts:

- The changes are not changing the current behaviour at all so it's possible to ship in a 2.x version with optional support for this.
- If someone would like to use the thumbprint as the kid the gem can be configured with `JWT.configuration.jwk.kid_generator_type = :rfc7638_thumbprint`. This will change the behaviour of the kid generation to generate the new kind of kids. The default value for this will be `JWT.configuration.jwk.kid_generator_type = :custom`
- In a future 2.x version we could add a deprecation warning on load that the defaults will change and explain what it means.

**Comment by anakinj** [comment]
@excpt ok to merge? No changes to the current behaviour and deprecation will happen at a later stage with some kind of warnings to the user.

**Review by excpt — APPROVED** [review]
Thank you! 👍

**Pull request merged**
