### PR TITLE
Adapt HMAC to JWK RSA code style.

### PR DESCRIPTION
**Pull request by phlegx**

### CODE REVIEW

**Comment by anakinj** [comment]
Not sure what is going on here but this PR has changes/commit already on master.

For example the commit [f4fdaad](https://github.com/jwt/ruby-jwt/pull/377/commits/f4fdaadfa659217739503a6b9f8866b64f4a2aa6) (Change class name Factory to KeyAbstract.) is [c5bf3376a](https://github.com/jwt/ruby-jwt/commit/c5bf3376a6ff8bd619bd724815d9e8e6bfc3accd) on master.

**Comment by anakinj** [comment]
To create a new branch in my fork i usually do this:
```
git remote add upstream https://github.com/jwt/ruby-jwt
git checkout master
git merge --ff upstream/master
git push origin master
git checkout -b my-new-feature
```

**Comment by phlegx** [comment]
@anakinj I have commited small changes to the same branch (phlegx:feature/jwk-hmac) and re-created a pull request.

**Comment by anakinj** [comment]
Maybe everything is in order. Im not claming I understand everything about git :)

The actual changes look good to me.

**Comment by phlegx** [comment]
:) yep! This was a very small change. So, you can merge to master if you want.

**Review by anakinj — APPROVED** [review]

**Comment by anakinj** [comment]
@phlegx I would suggest making a fresh branch from the latest master with the improvement. Cannot merge it from here at least.

**Comment by phlegx** [comment]
@anakinj what should I do? A new branch with my code and a new PR? Right?

**Comment by anakinj** [comment]
That is one option, another would just be a a rebase from upstream/master as @excpt suggested.

**Pull request closed without merging**
