### PR TITLE
Stricter RSA key generation from jwk parameters

### PR DESCRIPTION
**Pull request by anakinj**
This PR is addressing a parts of #523 and adding test coverage on a few scenarios. 

Moved the methods around a little for easier testing and added parameter validation with the rule:
 - If one of the optimisation params are given ALL needs to be given

As you @bellebaum pointed out the DER generation has some issues when parameters are missing. Did not dig that deep but I have a feeling that there is no way to present a private key in the DER format without these parameters.

Im a little unsure what do, not really eager into starting to calculate the primes etc. I guess it's doable but feels sketchy. 

So I guess the question is:

Is there a way to generate a usable RSA object with OpenSSL 3.0 with only the modulus and exponents (n,e,d)? as the JWK spec allows private keys to be presented with only these values.

### CODE REVIEW

**Comment by bellebaum** [comment]
I have asked about this over at the Ruby OpenSSL gem: https://github.com/ruby/openssl/issues/551
Seems like this is a TODO for them, so we should eventually see a way.

**Comment by anakinj** [comment]
Thanks @bellebaum for raising the question. Im going to return to this one to have it working with the adjustments from #520 at some point.

**Comment by anakinj** [comment]
This is the best we can to with the interfaces provided by the OpenSSL gem. The behaviour is going to be different depending on the version of openssl that is in use.

**Comment by anakinj** [comment]
Im going to merge this soonish.

Working on https://github.com/ruby/openssl/pull/555 to move all this heavy lifting into the openssl gem. Hopefully it will be great some day :)

**Pull request merged**
