### PR TITLE
Use RbNaCl for HMAC if available with fallback to OpenSSL

### PR DESCRIPTION
**Pull request by mwpastore**

### CODE REVIEW

**Comment by excpt** [comment]
For the 1.x version I will not add any new features. This PR is interesting for version 2.0.

**Comment by mwpastore** [comment]
Hi @excpt, I've rebased this to master if you're interested in including it in the 2.0 release. Let me know if you'd like any changes!

**Comment by excpt** [comment]
Thanks for the Rebase 👍

**Comment by mwpastore** [comment]
Yessir, thanks for the merge!

**Pull request merged**
