### PR TITLE
verifies algorithm before evaluating keyfinder

### PR DESCRIPTION
**Pull request by jb08**
[issue 343](https://github.com/jwt/ruby-jwt/issues/343) PR (coordinated with @zinosama)

### CODE REVIEW

**Comment by jb08** [comment]
CI failing unrelated to PR, no?
```
The command "bundle exec rspec && bundle exec codeclimate-test-reporter" exited with 1.
```

**Comment by jb08** [comment]
@ab320012 fyi here is the PR that was discussed as part of [issue 343](https://github.com/jwt/ruby-jwt/issues/343).

**Comment by jb08** [comment]
cc: @laurawyse @pjo336 @zinosama

**Comment by jb08** [comment]
@excpt @ab320012 any advice on how to push this forward?

**Comment by martinemde** [comment]
This looks good to me also. I made a change to the key loader and I'd also like to see this rolled into the next release with both our changes.

See #348

**Comment by jb08** [comment]
thanks @bdewater for the approval.

**Pull request merged**
