### PR TITLE
Documentation improvements

### PR DESCRIPTION
**Pull request by anakinj**
### Description

Improves documentation for various apis and adds deprecation warnings to apis about to get removed.

This also adds documentation generation for the public github pages, indirect fix for #407. On every push to main the documentation would get updated.

### Checklist

Before the PR can be merged be sure the following are checked:
* [x] There are tests for the fix or feature added/changed
* [x] A description of the changes and a reference to the PR has been added to CHANGELOG.md. More details in the [CONTRIBUTING.md](https://github.com/jwt/ruby-jwt/blob/main/CONTRIBUTING.md)

### CODE REVIEW

**Comment by janko** [comment]
@anakinj These changes break Rodauth, which references the `JWT::VERSION::{MAJOR,MINOR}` constants. I opened a [PR](https://github.com/jeremyevans/rodauth/pull/462) on Rodauth to use `JWT.gem_version` instead.

I was wondering if this change could possibly be reverted in the 2.x series, and delayed until 3.0. Or if at least these breaking changes could be documented in the changelog.

**Comment by anakinj** [comment]
For sure, I'll take a peek at this

**Comment by janko** [comment]
Appreciate the swift release! 🙏

**Comment by anakinj** [comment]
Thanks for pointing this out. Think these will stay public forever to have a backwards compatible way to check the version.

**Pull request merged**
