### PR TITLE
Support for ED25519

### PR DESCRIPTION
**Pull request by ab320012**
Added support + tests, readme section for eddsa algo ed25519 
https://github.com/jwt/ruby-jwt/issues/217

### CODE REVIEW

**Comment by ab320012** [comment]
method length + complexity for verify and arity of sign + verify eddsa methods follow the surrounding code convention. I can probably fix these but would have to modify existing code, let me know if this is ok

**Comment by excpt** [comment]
@ab320012 Thank you for the PR!

Refactoring the code to reduce the arity and other code smells should happen in a different PR. Don't do it in this PR.

Reviewing you code now.

**Comment by ab320012** [comment]
@excpt Thanks, will add that one after this one closes. Wondering if class based solution will make more sense. 

```ruby 
# lib/jwt/algos/hmac.rb
class Hmac
   # other classes same structure: ecdsa, eddsa, rsa
  TYPES= %w(HS256 HS512256 HS384 HS512).freeze 
 def initialize; end 
 def sign (signing_input); end
 def verify(verifying_input); end 
end

# signing_input and verifying_input will be refactored into a struct 

#lib/signature.rb 
Signed = Struct.new(:algo, :key, :msg) 
Verified = Struct.new(:algorithm, :public_key, :signing_input, :signature)
```

Let me know if something like this is ok with you for next PR

**Comment by excpt** [comment]
@ab320012 That's the way to go. Most important: the two signatures of the main methods `JWT.encode` and `JWT.decode` need to stay the same. Everything else is code behind and that should not break anything for the users.

**Pull request merged**
